-- MySQL Script generated by MySQL Workbench
-- Wed Mar 25 05:11:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todo_list_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todo_list_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todo_list_app` DEFAULT CHARACTER SET utf8 ;
USE `todo_list_app` ;

-- -----------------------------------------------------
-- Table `todo_list_app`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_list_app`.`user` (
  `id_use` INT NOT NULL AUTO_INCREMENT,
  `mai_use` VARCHAR(50) NULL,
  `pas_use` VARCHAR(45) NULL,
  `sta_use` CHAR(1) NULL,
  PRIMARY KEY (`id_use`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_list_app`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_list_app`.`color` (
  `id_col` INT NOT NULL AUTO_INCREMENT,
  `cod_col` VARCHAR(16) NULL COMMENT 'Code of the color, HEX',
  `sta_col` CHAR(1) NULL,
  PRIMARY KEY (`id_col`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_list_app`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_list_app`.`category` (
  `id_cat` INT NOT NULL AUTO_INCREMENT,
  `nam_cat` VARCHAR(45) NULL COMMENT 'Name of Category',
  `stat_cat` CHAR(1) NULL COMMENT 'Status of the Category',
  `fky_color` INT NULL,
  PRIMARY KEY (`id_cat`),
  CONSTRAINT `fky_color_cat`
    FOREIGN KEY (`id_cat`)
    REFERENCES `todo_list_app`.`color` (`id_col`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_list_app`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_list_app`.`task` (
  `id_task` INT NOT NULL AUTO_INCREMENT,
  `nam_task` VARCHAR(45) NULL COMMENT 'Name of the task',
  `des_task` VARCHAR(250) NULL COMMENT 'Description of the task(optional)',
  `dat_task` DATE NULL COMMENT 'Task date',
  `tim_task` TIME NULL COMMENT 'Time of the task (optional)',
  `fky_category` INT NULL,
  `fky_color` INT NULL,
  `fky_user` INT NULL,
  `sta_imp_task` CHAR(1) NULL COMMENT 'Status of importance:\nI=Important\nN=normal',
  `sta_task` CHAR(1) NULL COMMENT 'Status of the task:\nC=Complete\nI=Incomplete\n\nDefault Vale \"I\"',
  PRIMARY KEY (`id_task`),
  INDEX `fky_categoria_idx` (`fky_category` ASC),
  INDEX `fky_usuario_idx` (`fky_user` ASC),
  INDEX `fky_color_idx` (`fky_color` ASC),
  CONSTRAINT `fky_categoria_task`
    FOREIGN KEY (`fky_category`)
    REFERENCES `todo_list_app`.`category` (`id_cat`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fky_user_task`
    FOREIGN KEY (`fky_user`)
    REFERENCES `todo_list_app`.`user` (`id_use`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fky_color_task`
    FOREIGN KEY (`fky_color`)
    REFERENCES `todo_list_app`.`color` (`id_col`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_list_app`.`list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_list_app`.`list` (
  `id_lis` INT NOT NULL AUTO_INCREMENT,
  `nam_lis` VARCHAR(45) NULL COMMENT 'Name of the object in the list',
  `fky_task` INT NULL,
  `sta_lis` CHAR(1) NULL COMMENT 'Status of the list:\nC=Complete\nI=Icomplete\n\ndefault value it will be \"I\"',
  PRIMARY KEY (`id_lis`),
  INDEX `fky_task_idx` (`fky_task` ASC),
  CONSTRAINT `fky_task_lis`
    FOREIGN KEY (`fky_task`)
    REFERENCES `todo_list_app`.`task` (`id_task`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_list_app`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_list_app`.`notification` (
  `id_not` INT NOT NULL AUTO_INCREMENT,
  `dat_not` DATE NULL COMMENT 'Notification date',
  `tim_not` TIME NULL COMMENT 'Notification time',
  `fky_task` INT NULL,
  `sta_not` CHAR(1) NULL COMMENT 'A=Active\nI=Inactive',
  PRIMARY KEY (`id_not`),
  INDEX `fky_task_idx` (`fky_task` ASC),
  CONSTRAINT `fky_task_not`
    FOREIGN KEY (`fky_task`)
    REFERENCES `todo_list_app`.`task` (`id_task`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
